In [2]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Tensors refresher

# create a tensor , a scaler to be more specific
scaler  = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.item()

7

In [5]:
scaler.ndim 

0

In [6]:
## vector

vector = torch.tensor([7,7])
print(vector.ndim)

1


In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix creation

matrix = torch.tensor([[7, 9],
                       [10,11]])

print(f"the dimension is {matrix.ndim}")
print(f"the shape is {matrix.shape}")

the dimension is 2
the shape is torch.Size([2, 2])


In [9]:
matrix

tensor([[ 7,  9],
        [10, 11]])

In [10]:
# Tensors now

TENSORS = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
print(f"the dimension of the tensor is: {TENSORS.ndim}")
print(f"the shape of the tensor is: {TENSORS.shape}")

the dimension of the tensor is: 3
the shape of the tensor is: torch.Size([1, 3, 3])


The smallest unit we can have is a scaler. which is just a number. then we can proceed to having a vector which basically has magnitude and direction. we can also move a step further by collecting these vectors to form a matrix. then finally a collection of these matrices can help us form a tensor. Tensors are very important in our work with deep learning especially when we're working with images

In [11]:
TENSORS[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
## Random Tensors

random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.9487, 0.9232, 0.6741, 0.5938],
         [0.8257, 0.2870, 0.5372, 0.9608],
         [0.8082, 0.3049, 0.9447, 0.0116]],

        [[0.1728, 0.6574, 0.9368, 0.7741],
         [0.0765, 0.9216, 0.2743, 0.1189],
         [0.9654, 0.1271, 0.2050, 0.3609]]])

In [13]:
random_tensor.ndim

3

In [14]:
# create a random tensor with similar shape to an image tensor

rand_image_size_tensor = torch.rand(size=(3,224,224)) # color channel(RGB), height and width
rand_image_size_tensor.shape, rand_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Why Tensors?

` Neural networks start with random numbers, then adjust it after looking at data and repeat the process. so it's usually like this: random numbers -> look at data -> update random numbers -> repeat`

In [15]:
## Zeros and Ones

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
# for ones
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [17]:
# create a range  of tensors

range_tensor = torch.arange(0, 10,1)
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# tensors like. i can create zeroes or ones tensors from an existing tensor if i 
# just want to replicate the size of the previous tensor in the new one

ten_zeroes = torch.zeros_like(input=range_tensor)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Data types

**Note:** Tensors data types usually give errors when expressed in the wrong form.

1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device

The first error arises when we try to do an operation  with a tensor that is not in
the supported or detected state.

The second is the same error we would get say we try to multiply matrices of incompatible dimensions

The third error arises if you're trying to do operations between tensors and they live in different devices. Say for example you have a tensor in the cpu and you're trying to carryout an operation with one on the gpu, it will definitely throw you an error

In [19]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,# by default it takes float 32
                               device=None, # what device is your tensor on
                               requires_grad=False)# whether to track gradients with this tensors operations
float_32_tensor.dtype

torch.float32

In [20]:
# create a float 16 tensor
float_16_tensors = float_32_tensor.type(torch.float16)
float_16_tensors

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors

1. To get the datatype from tensors use: `tensor.dtypes`
2. To get the shape use : `tensor.shape`
3. To get to know which device the tensor is on use `tensor.device`


In [21]:
# practice this with some random tensor
practice_tensor = torch.rand(size=(3,5))
practice_tensor

tensor([[0.0634, 0.4171, 0.2408, 0.5835, 0.4716],
        [0.0907, 0.5875, 0.1983, 0.1873, 0.5869],
        [0.4295, 0.8759, 0.5973, 0.8371, 0.0198]])

In [22]:
# Get more information about the tensor from the attributes
print(f"Datatype of the tensor: {practice_tensor.dtype}")
print(f"Shape of the tensor: {practice_tensor.shape}")
print(f"Device where the tensor is located : {practice_tensor.device}")

Datatype of the tensor: torch.float32
Shape of the tensor: torch.Size([3, 5])
Device where the tensor is located : cpu


### Manipulating Tensors, Tensor Operations.

1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication

In [23]:
# create  a tensor and add a number to it.
tensor_1 = torch.tensor([1,2,3,4])
tensor_1 + 100


tensor([101, 102, 103, 104])

In [24]:
# Multiply tensors
tensor_2 = tensor_1 * 10
tensor_2

tensor([10, 20, 30, 40])

In [25]:
# Torch in-built functions
torch.mul(tensor_1, 10)

tensor([10, 20, 30, 40])

In [26]:
# Tensor aggregation

x = torch.arange(0,100,10)
x
 

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [27]:
# find the min value
torch.min(x), x.min()

(tensor(0), tensor(0))

In [28]:
# find the max value
torch.max(x), x.max()

(tensor(90), tensor(90))

In [29]:
# Find the mean
# first this gave an error. because it doesnn't work with int64 which is said to be the long
# to solve this, we need to convert it float32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

# the torch.mean() requires a datatype of float32

(tensor(45.), tensor(45.))

In [30]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [31]:
# argmax and argmin find the position of the max and min values of a tensor.

### other operations we can do on our tensors are:
1. Reshape
2. View
3. Stacking - combining multiple tensor on top of each other or side by side
4. Squeeze - remove all `1` dimensions from a tensor
5. Unsqueeze - add a `1` dimension to a target tensor
6. permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [32]:
x = torch.arange(1,11)
x_stacked = torch.stack([x,x,x], dim=1)
x, x_stacked

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([[ 1,  1,  1],
         [ 2,  2,  2],
         [ 3,  3,  3],
         [ 4,  4,  4],
         [ 5,  5,  5],
         [ 6,  6,  6],
         [ 7,  7,  7],
         [ 8,  8,  8],
         [ 9,  9,  9],
         [10, 10, 10]]))

In [33]:
# squeeze and unsqueeze
x_squeezed = torch.squeeze(x)
x_unsqueezed = torch.unsqueeze(x,dim=0)

x_squeezed.shape, x_unsqueezed.shape

(torch.Size([10]), torch.Size([1, 10]))

In [34]:
x_new = torch.zeros(2,1,2,1,2)
x_new.size()

torch.Size([2, 1, 2, 1, 2])

In [35]:
y = torch.squeeze(x_new)
y.size(), y

(torch.Size([2, 2, 2]),
 tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]))

In [36]:
y = torch.squeeze(x_new, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [37]:
# torch.permute() - rearrages the dimensions of a target tensor in a specified order

x = torch.rand(2,3,5)
x.size()

torch.Size([2, 3, 5])

In [38]:
torch.permute(x,(2,0,1)).shape

torch.Size([5, 2, 3])

In [39]:
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# permute the original tensor
x_permuted = x_original.permute(2,1,0) # swapped axis 0 with 2, rearranged it.
print(f"The previous shape: {x_original.shape}") # [height, width, color_channels]
print(f"The permuted shape is: {x_permuted.shape}") # [color_channels, height, width]

The previous shape: torch.Size([224, 224, 3])
The permuted shape is: torch.Size([3, 224, 224])


In [40]:
# indexing of tensors
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [41]:
# let's index and change a value within the tensor

x[0][0][2] = 20
x

tensor([[[ 1,  2, 20],
         [ 4,  5,  6],
         [ 7,  8,  9]]])

In [42]:
x[0,0,2] = 30
x

tensor([[[ 1,  2, 30],
         [ 4,  5,  6],
         [ 7,  8,  9]]])

In [43]:
# get number 9 out from the tensor
x[0,2,2]

tensor(9)

In [44]:
# NumPy array to tensors
arr = np.arange(1, 10)
tensors = torch.from_numpy(arr)
print(f"this is the numpy array : {arr.dtype}")
print(f"This is the tensors from numpy: {tensors.dtype}")
''''
it is important to note that by default, the datatype for tensors is float32.
However we see int64 here because it is inheriting the default datatype of the
numpy array it took.
'''

this is the numpy array : int32
This is the tensors from numpy: torch.int32


"'\nit is important to note that by default, the datatype for tensors is float32.\nHowever we see int64 here because it is inheriting the default datatype of the\nnumpy array it took.\n"

In [45]:
# Tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
print(f"The datatype of the original tensor: {tensor.dtype}")
print(f"The datatype of the numpy is : {numpy_tensor.dtype}")
''' 
Like the previous case, the default data type for the numpy is inherited 
from the previous one it was converted from.
'''

The datatype of the original tensor: torch.float32
The datatype of the numpy is : float32


' \nLike the previous case, the default data type for the numpy is inherited \nfrom the previous one it was converted from.\n'

In [46]:
# check for GPU access with pytorch
torch.cuda.is_available()

False

In [47]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

It is worthy to note that if the tensor is on the GPU, we can't transform it to NumPy.

First we need to copy the tensor to the cpu and then do the conversion there